import { GameData, AnalysisReport, ImprovementTip, Channel } from './types'

export const MOCK_GAMES: Record<string, { game: GameData; analysis: AnalysisReport; tips: ImprovementTip[]; channels: Channel[] }> = {
  '1': {
    game: {
      name: 'Hollow Knight',
      description: 'A challenging 2D action-adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and uncover ancient history at the kingdom\'s heart.',
      tags: ['Metroidvania', 'Platformer', 'Action', 'Indie', '2D', 'Difficult', 'Dark Fantasy', 'Atmospheric'],
      similarGames: ['Ori and the Blind Forest', 'Dead Cells', 'Celeste', 'Salt and Sanctuary'],
      estimatedOwners: '5,000,000 .. 10,000,000',
      price: 14.99,
      steamAppId: '367520',
      headerImageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
      steamUrl: 'https://store.steampowered.com/app/367520',
    },
    analysis: {
      audienceProfile: 'Core gamers aged 18–34 who thrive on punishing-but-fair challenges and love getting lost in hand-crafted, atmospheric worlds. They\'ve played Dark Souls and want that same feeling in a 2D format. They share speedruns, fan art, and hidden-lore discussions on Reddit and Discord.',
      keywords: ['metroidvania', 'hollow knight', 'soulslike 2d', 'indie platformer', 'dark fantasy', 'atmospheric platformer'],
      chineseKeywords: ['银河恶魔城', '空洞骑士', '类魂2D游戏', '独立平台游戏', '暗黑奇幻', '大气平台游戏'],
      whyTheyWillLoveIt: 'The same dopamine hit as defeating a Soulsborne boss, in an artistically stunning underground world that rewards curiosity.',
    },
    tips: [
      { title: 'Lead With Difficulty', suggestion: 'Add "For fans of Dark Souls" prominently in the first sentence of your description to attract the target audience immediately.', impact: 'high' },
      { title: 'Showcase the Art in Screenshots', suggestion: 'Replace 3 of your current screenshots with close-up boss fight moments that highlight the hand-drawn animation quality.', impact: 'high' },
      { title: 'Add "Metroidvania" as Primary Tag', suggestion: '"Metroidvania" is searched 4× more than "Platformer" by your target buyers — ensure it is your first tag.', impact: 'medium' },
    ],
    channels: [
      {
        id: 'UCls_vBtHOcFRQMk-pJaQeGA',
        platform: 'youtube_creator',
        name: 'Wanderbots',
        url: 'https://youtube.com/channel/UCls_vBtHOcFRQMk-pJaQeGA',
        followerCount: 312000,
        followerLabel: 'subscribers',
        recentContent: ['Hollow Knight: Silksong NEW Footage Reaction', 'Top 10 Metroidvanias 2024', 'Dead Cells Ascension DLC Review'],
        relevanceReason: 'Specializes in metroidvania and indie platformers; audience overlaps exactly with Hollow Knight fans.',
      },
      {
        id: 'reddit_metroidvania',
        platform: 'reddit',
        name: 'r/metroidvania',
        url: 'https://reddit.com/r/metroidvania',
        followerCount: 185000,
        followerLabel: 'members',
        relevanceReason: 'Dedicated community that actively seeks and reviews new metroidvania releases.',
      },
      {
        id: 'media_rps',
        platform: 'gaming_media',
        name: 'Rock Paper Shotgun',
        url: 'https://www.rockpapershotgun.com',
        followerCount: 1500000,
        followerLabel: 'monthly readers',
        relevanceReason: 'Consistently covers indie games of this type with long-form reviews that drive Steam sales.',
      },
    ],
  },
  '2': {
    game: {
      name: 'Stardew Valley',
      description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?',
      tags: ['Farming Sim', 'RPG', 'Pixel Graphics', 'Relaxing', 'Singleplayer', 'Multiplayer', 'Cute', 'Casual'],
      similarGames: ['My Time At Portia', 'Slime Rancher', 'Spiritfarer', 'Graveyard Keeper'],
      estimatedOwners: '20,000,000 .. 50,000,000',
      price: 14.99,
      steamAppId: '413150',
      headerImageUrl: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
      steamUrl: 'https://store.steampowered.com/app/413150',
    },
    analysis: {
      audienceProfile: 'Casual and mid-core players aged 16–40, leaning female, who want a relaxing escape from daily stress. They watch cozy gaming streams on Twitch, follow cottagecore aesthetics on TikTok and Xiaohongshu, and share farm layout screenshots in Discord servers.',
      keywords: ['cozy game', 'farming sim', 'stardew valley', 'relaxing game', 'life simulation', 'pixel art rpg'],
      chineseKeywords: ['治愈系游戏', '农场模拟', '星露谷物语', '放松游戏', '生活模拟', '像素RPG'],
      whyTheyWillLoveIt: 'A sun-drenched digital escape where every day ends with something to look forward to — no pressure, just peace.',
    },
    tips: [
      { title: 'Highlight Multiplayer in Header', suggestion: 'Your header image shows solo gameplay; use a co-op farm scene since multiplayer drives 30%+ of discovery for life sims.', impact: 'high' },
      { title: 'Target "Cozy Games" Tag', suggestion: 'Add "Cozy" as a tag — it\'s the fastest growing discovery keyword in the life sim category since 2022.', impact: 'high' },
      { title: 'Seasonal Pricing Events', suggestion: 'With 50M+ owners the game is mature; flash discounts during Steam events still spike wishlist conversions by 15%.', impact: 'medium' },
    ],
    channels: [
      {
        id: 'UC5c_HB7bFwFkHIizmNEq7Ew',
        platform: 'youtube_creator',
        name: 'GamingWithJen',
        url: 'https://youtube.com/channel/UC5c_HB7bFwFkHIizmNEq7Ew',
        followerCount: 220000,
        followerLabel: 'subscribers',
        recentContent: ['New Cozy Game Recommendations 2024', 'Stardew Valley 1.6 Farm Tour', '10 Farming Games Better Than Stardew'],
        relevanceReason: 'Cozy-gaming focused creator whose audience actively seeks new farming and life sim games.',
      },
      {
        id: 'reddit_cozygamers',
        platform: 'reddit',
        name: 'r/cozygamers',
        url: 'https://reddit.com/r/cozygamers',
        followerCount: 320000,
        followerLabel: 'members',
        relevanceReason: 'Community purpose-built for discovering new cozy and farming games.',
      },
    ],
  },
}
